#!/bin/bash

read -p "Type 1 to sort by memory, Type 2 to sort by CPU consumption: " input

echo "Processes for user $USER"
echo ""

if [ $input == 1 ]
then
 ps aux --sort -%mem | grep -e "^$USER"
else
 ps aux --sort -%cpu | grep -e "^$USER"
fi
